set shell := ["powershell.exe", "-c"]

BUILD_DIR_DEBUG := "cmake-build-debug"
BUILD_DIR_RELEASE := "cmake-build-release"

[windows]
build mode="release":
    @cmake -S . -B {{
        if mode == "release" { BUILD_DIR_RELEASE } else { BUILD_DIR_DEBUG }
    }} -G Ninja -DCMAKE_BUILD_TYPE={{
        if mode == "release" { "Release" } else { "Debug" }
    }}

    @cmake --build {{
        if mode == "release" { BUILD_DIR_RELEASE } else { BUILD_DIR_DEBUG }
    }}

[windows]
clean:
    @rm -r cmake-build-*

install: (build "release")
    @cmake --install {{BUILD_DIR_RELEASE}} --prefix package