name: Build & Test

on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: read

env:
  NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"
          source-url: https://nuget.pkg.github.com/Castor-Studio/index.json

      - name: Restore
        run: dotnet restore Castor-Studio.sln

      - name: Build
        run: dotnet build Castor-Studio.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Castor-Studio.sln --configuration Release --no-build --no-restore
